name: update dependencies
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun.sh
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Update dependencies
        run: |
          bun update
          bun install

      - name: Commit updates
        run: |
          git config user.name "actions[bot]"
          git config user.email "actions[bot]@git.z0x.ca"
          git add .
          if git diff --staged --quiet; then
            echo "No updates avalable"
          else
            git commit -m "chore(deps): bump dependencies"
            git push
          fi
